### ISSUE TITLE
Set up environment, variables, parameters, data profiling to deploy SSIS packages

### ISSUE THREAD

**Issue by thieukhanhlinh** [dhuy237/fa-project-1-team-7#24]

**Comment by huynguyen314** [comment]
@thieukhanhlinh Please run SsisTestingV1 package that I added on our repo

**Comment by thieukhanhlinh** [comment]
Ok Huy, done

**Comment by thieukhanhlinh** [comment]
Just renamed some tasks

**Comment by thieukhanhlinh** [comment]
Please pull SSISTEST_V2 to review, Huy!

**Comment by huynguyen314** [comment]
> Please pull SSISTEST_V2 to review, Huy!

Okay.

**Comment by thieukhanhlinh** [comment]
we had all of them: environment, variables, parameters, data profiling! Done!

**Comment by huynguyen314** [comment]
Please upload the last version off SSIS package.

**Comment by huynguyen314** [comment]
After uploading, please close this issue!

**Comment by thieukhanhlinh** [comment]
pushed it already!
