### ISSUE TITLE
Deploy package, set up environment variables in SSIS Catalog

### ISSUE THREAD

**Issue by huynguyen314** [dhuy237/fa-project-1-team-7#25]
Deploy SSIS package on SQL Server and set up environment variables  to run it automatically.

**Comment by thieukhanhlinh** [comment]
I deployed and executed successfully!

**Comment by huynguyen314** [comment]
You are so cool!

**Comment by huynguyen314** [comment]
May I close this issue?

**Comment by thieukhanhlinh** [comment]
okie!

**Comment by huynguyen314** [comment]
Thanks my friend!
