### ISSUE TITLE
Set up tasks on snowflake

### ISSUE THREAD

**Issue by huynguyen314** [dhuy237/fa-project-1-team-7#29]
Create tasks to load data

**Comment by huynguyen314** [comment]
@thieukhanhlinh Please give your comment on the codes that I set up tasks on snowflake in init_snowflake file.

**Comment by thieukhanhlinh** [comment]
okie la

**Comment by huynguyen314** [comment]
Is it OK?

**Comment by thieukhanhlinh** [comment]
yep, pls close this task!

**Comment by huynguyen314** [comment]
Ok. I will close this issue.
