### ISSUE TITLE
Create Power BI dashboard

### ISSUE THREAD

**Issue by huynguyen314** [dhuy237/fa-project-1-team-7#30]
Create dashboard with data loading from snowflake

**Comment by thieukhanhlinh** [comment]
I just uploaded the dashboard version 4, please check it!

**Comment by huynguyen314** [comment]
> I just uploaded the dashboard version 4, please check it!

I will check it ASAP

**Comment by thieukhanhlinh** [comment]
I added some details, pull to check pls!

**Comment by thieukhanhlinh** [comment]
hold a minute, I am pushing the final version!

**Comment by thieukhanhlinh** [comment]
pls pull the dashboard!

**Comment by huynguyen314** [comment]
Please upload the last version and close this issue.

**Comment by thieukhanhlinh** [comment]
okie
